name: Test

on:
  pull_request:
    branches: [ main ]
  push:
    branches: [ main ]

env:
  GOVERSION: 1.26.0
  GONOSUMDB: github.com/paperspell

jobs:
  golangci-lint:
    name: Lint Check
    runs-on: ubuntu-latest
    steps:
      - name: Check out the code
        uses: actions/checkout@v6

      - name: Setup Go
        uses: actions/setup-go@v6
        with:
          go-version: ${{ env.GOVERSION }}
          cache: true

      - name: Set up private repository access
        env:
          GITHUB_TOKEN: ${{ secrets.GH_PAT }}
        run: |
          echo "machine github.com login $GITHUB_TOKEN" > ~/.netrc
          git config --global url."https://${GITHUB_TOKEN}@github.com/".insteadOf "https://github.com/"

      - name: Cache golangci-lint
        uses: actions/cache@v5
        with:
          path: |
            ~/.cache/golangci-lint
          key: ${{ runner.os }}-golangci-lint-${{ env.GOLANGCI_LINT_VERSION }}

      - name: golangci-lint
        run: |
          curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sh -s -- -b $(go env GOPATH)/bin ${{ env.GOLANGCI_LINT_VERSION }}
          golangci-lint --version
          golangci-lint run --verbose

  unit-test:
    name: Unit Test
    runs-on: ubuntu-latest
    steps:
      - name: Check out the code
        uses: actions/checkout@v6
        with:
          fetch-depth: 0

      - name: Setup Go
        uses: actions/setup-go@v6
        with:
          go-version: ${{ env.GOVERSION }}
          cache: true

      - name: Set up private repository access
        env:
          GITHUB_TOKEN: ${{ secrets.GH_PAT }}
        run: |
          echo "machine github.com login $GITHUB_TOKEN" > ~/.netrc
          git config --global url."https://${GITHUB_TOKEN}@github.com/".insteadOf "https://github.com/"

      - name: Run tests
        run: |
          make test

  migration-test:
    name: Migration Test
    runs-on: ubuntu-latest
    steps:
      - name: Check out the code
        uses: actions/checkout@v6
        with:
          fetch-depth: 0

      - name: Setup Go
        uses: actions/setup-go@v6
        with:
          go-version: ${{ env.GOVERSION }}
          cache: true

      - name: Set up private repository access
        env:
          GITHUB_TOKEN: ${{ secrets.GH_PAT }}
        run: |
          echo "machine github.com login $GITHUB_TOKEN" > ~/.netrc
          git config --global url."https://${GITHUB_TOKEN}@github.com/".insteadOf "https://github.com/"

      - name: Run migration tests
        run: |
          make test-migrations
